---
encoding: utf8
default_branch: main
sections:
  - [features, New Features, 1]
  - [features_expnew, New Experiments, 2]
  - [features_explib, Experiment Library Updates, 2]
  - [features_expclass, Experiment Class Features, 2]
  - [features_analysis, Analysis Class Features, 2]
  - [features_expdata, Experiment Data Features, 2]
  - [features_curvefit, Curve Fit Features, 2]
  - [features_calibration, Calibration Features, 2]
  - [features_visualization, Visualization Features, 2]
  - [issues, Known Issues]
  - [upgrade, Upgrade Notes, 1]
  - [upgrade_package, Package Upgrades, 2]
  - [upgrade_explib, Experiment Library Upgrades, 2]
  - [upgrade_expclass, Experiment Class Upgrades, 2]
  - [upgrade_analysis, Analysis Class Upgrades, 2]
  - [upgrade_expdata, Experiment Data Upgrades, 2]
  - [upgrade_curvefit, Curve Fit Upgrades, 2]
  - [upgrade_calibration, Calibration Upgrades, 2]
  - [upgrade_visualization, Visualization Upgrades, 2]
  - [deprecations, Deprecation Notes]
  - [critical, Critical Issues]
  - [security, Security Issues]
  - [fixes, Bug Fixes]
  - [fixes_package, Package Fixes, 2]
  - [fixes_explib, Experiment Library Fixes, 2]
  - [fixes_expclass, Experiment Class Fixes, 2]
  - [fixes_analysis, Analysis Class Fixes, 2]
  - [fixes_expdata, Experiment Data Fixes, 2]
  - [fixes_curvefit, Curve Fit Fixes, 2]
  - [fixes_calibration, Calibration Fixes, 2]
  - [fixes_visualization, Visualization Fixes, 2]
  - [developer, API Changes for Experiment Authors]
  - [other, Other Notes]
template: |
          ---
          prelude: >
              Replace this text with content to appear at the top of the section for this
              release. All of the prelude content is merged together and then rendered
              separately from the items listed in other parts of the file, so the text
              needs to be worded so that both the prelude and the other items make sense
              when read independently. This may mean repeating some details. Not every
              release note requires a prelude. Usually only notes describing major
              features or adding release theme details should have a prelude.
          features:
            - |
              List new features here, or remove this section.  All of the list items in
              this section are combined when the release notes are rendered, so the text
              needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
          issues:
            - |
              List known issues here, or remove this section.  All of the list items in
              this section are combined when the release notes are rendered, so the text
              needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
          upgrade:
            - |
              List upgrade notes here, or remove this section.  All of the list items in
              this section are combined when the release notes are rendered, so the text
              needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
          deprecations:
            - |
              List deprecations notes here, or remove this section.  All of the list
              items in this section are combined when the release notes are rendered, so
              the text needs to be worded so that it does not depend on any information
              only available in another section, such as the prelude. This may mean
              repeating some details.
          critical:
            - |
              Add critical notes here, or remove this section.  All of the list items in
              this section are combined when the release notes are rendered, so the text
              needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
          security:
            - |
              Add security notes here, or remove this section.  All of the list items in
              this section are combined when the release notes are rendered, so the text
              needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
          fixes:
            - |
              Add normal bug fixes here, or remove this section.  All of the list items
              in this section are combined when the release notes are rendered, so the
              text needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
          developer:
            - |
              Add upgrade of protected-level API (e.g. hooks). All of the list items
              in this section are combined when the release notes are rendered, so the
              text needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
          other:
            - |
              Add other notes here, or remove this section.  All of the list items in
              this section are combined when the release notes are rendered, so the text
              needs to be worded so that it does not depend on any information only
              available in another section, such as the prelude. This may mean repeating
              some details.
earliest_version: 0.1.0
